logging:
  file:
    path: ./logs/
    name: ${logging.file.path}cps-middleware-skeleton.log
  level:
    org:
      springframework:
        context: INFO
        web: INFO
    root: INFO
  pattern:
    file: '%d [%level] %c{1.} [%t] %m%n'

org:
  osgi:
    framework:
      bootdelegation: com.sun.*

server:
  port: 8092
  servlet:
    context-path: /cps

spring:
  application:
    name: airline-strategic-dashboard
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 180000
      maximum-pool-size: 10
      minimum-idle: 2
    password: Unisys123*
    url: jdbc:sqlserver://172.29.110.248:1433;databaseName=CPS;encrypt=false;
    username: cps
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cpsprodloginrealm

# swagger-ui custom path
springdoc:
  swagger-ui:
  path: /swagger-ui.html